### ISSUE TITLE
fatal error: opening dependency file /*.d: Permission denied

### ISSUE THREAD

**Issue by crissmath** [GreenWaves-Technologies/gap_sdk#309]
Hello everyone, I have been working on a project with gap8, which worked correctly in Release v4.0.0.

I had to install the SDK on another machine, so I installed the latest version, and when I tried to compile:

```
> make clean all 
.
.
.
At top level:
test.c:832:1: fatal error: opening dependency file /test.d: Permission denied
 }
```

- I've modified the Makefile the same as some of the examples, but I can't find an example in the new SDK that uses:

 `~/gap_sdk/utils/rules/pulp_rules.mk`

- I also noticed that when trying to run the benchmarks example, it is located in the directory.

`~/gap_sdk/benchmarks/gap8/cnn$ make clean all`

- have the same problem:

```
`~/gap_sdk/benchmarks/gap8/cnn$ make clean all`

AllTest.c: At top level:
AllTest.c:1323:1: fatal error: opening dependency file /AllTest.d: Permission denied
 }
 ^
```

I have installed the SDK on several occasions, and the examples with pmsis work correctly.
```
~/gap_sdk/examples/pmsis/helloworld$
.
.
.
………………………….
[0 7] Hello World!
    Cluster master core exit
    Test success!
```

I've also tried rolling back a previous release(4.0.0) that included the examples, but I can't get it to work.

Thanks.....

**Comment by crissmath** [comment]
anyone having a similar problem ??

**Comment by crissmath** [comment]
I have found a problem in my makefile, and it had confusion with the rules that I was using.

Now everything works correctly.
